version: '3.8'

services:
  db:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - "6060:6060"
  
  app:
    container_name: app
    restart: on-failure
    ports:
      - "3030:3030"

    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile