version: '3.8'

services:
  app:
    container_name: app
    restart: on-failure
    ports:
      - "3030:3030"

    depends_on:
      - db

    volumes:
      - ./src:/src

    build:
      context: .
      dockerfile: Dockerfile
          
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - "6060:6060"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=db_password
    volumes:
      - db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=database
      - MB_DB_USER=database
      - MB_DB_PASS=db_password
      - MB_DB_HOST=db
      - MB_DB_FILE=/metabase-data/metabase.db

      - MB_DB_PORT=5432

    depends_on:
        - db
    volumes:
        - metabase_data:/metabase-data
    ports:
      - 5432:5432

volumes:
  db_data:
  metabase_data: